# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer4.ulaw.com:
    extends:
      file:   ../base/orderer-base.yaml
      service: orderer-base
    container_name: orderer4.ulaw.com
    volumes:
    - ../../artifacts/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../../artifacts/crypto-config/ordererOrganizations/ulaw.com/orderers/orderer4.ulaw.com/msp:/var/hyperledger/orderer/msp
    - ../../artifacts/crypto-config/ordererOrganizations/ulaw.com/orderers/orderer4.ulaw.com/tls/:/var/hyperledger/orderer/tls